Merge dev branch to master
Chatterjee-31/C-lings pull request #4
Opened 2020-07-03 20:24 UTC by Vishwaak

The dev branch is rebased properly over the master branch.

2020-07-03 20:27 UTC, vibhoothi requested changes
Please cleanup the commits,
It has lot of noise,

What I would suggest is 
- [x] Soft reset all 7
- [x] Have a single commit which explains the details what you did short and precise.

2020-07-04 16:32 UTC, vibhoothi reviewed
Commit messages seems fine but still, it is not able to watch/verify.

<Details>

```c
vibhoothiiaanand@derpBox /V/b/m/C-lings (dev) [255]> ./test verify
problem-
���
/Volumes/buildBox/misc/C-lings/Problems/1.c
���
/Volumes/buildBox/misc/C-lings/Problems/2.c
���
/Volumes/buildBox/misc/C-lings/Problems/3.c
���
/Volumes/buildBox/misc/C-lings/Problems/a.out
clang: error: no such file or directory: '���'
clang: error: no input files
sh: line 1: /Volumes/buildBox/misc/C-lings/Problems/2.c: No such file or directory

problem not compiled,
 solve error to compile
 for hint type <problem.hint>
```
</Details>

2020-07-04 17:40 UTC, Vishwaak commented
There seems to be no issue with, watch/verify command in my setup. Also seems to work with clang-10 with no issue.

2020-07-06 10:09 UTC, akshayaky requested changes
The lines are not properly indented and different brace placement styles are used throughout the code. Fixing these would improve Code Readability.

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +        printf("Commnad not found \n");
Typo here

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +	    compile(directory);
Not aligned.

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +	for(int j=1; j<exe_cnt; j++)
Not aligned.

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +    printf("%s \n",files);
Not aligned.

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +	printf("\n Total command after strcats: %s \n", command);
Not aligned.

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +    }
- Uneven indentation.  
 - Better to use a single style of Brace Placement

2020-07-06 10:09 UTC, akshayaky commented on compile.c
> +    }
Brace placement is different from the rest.

2020-07-06 14:45 UTC, merged